[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
truestory = "3dupjHU543SdKpSkdTyPSbPLAowgTPRT15jG2rJd9fD1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/jatin/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
