[toolchain]
anchor_version = "0.29.0"
[features]
seeds = false
skip-lint = false

[programs.localnet]
truestory = "3dupjHU543SdKpSkdTyPSbPLAowgTPRT15jG2rJd9fD1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/jatin/.config/solana/id.json"

[programs.devnet]
truestory = "3dupjHU543SdKpSkdTyPSbPLAowgTPRT15jG2rJd9fD1"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
